services:
  tmp:
    image: busybox
    command: chmod -R 777 /tmp/docker
    volumes:
      - /tmp/docker/:/tmp/docker/

  redis:
    image: redis/redis-stack
    volumes:
      - ./redis-stack.conf:/redis-stack.conf
    volumes_from:
      - tmp
