[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.4.3"
log = "0.4.20"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dioxus-desktop = "0.4.3"
pretty_env_logger = "0.5.0"
