[package]
name = "orderbook"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
libc = "0.2"
libffi = { git = "https://github.com/marcustut/libffi-rs.git" }
thiserror = "1.0.61"

[build-dependencies]
bindgen = "0.69"
